sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t narcisonunez/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true narcisonunez/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'Docker React'
  env: 'Dockerreact-env'
  bucket_name: 'elasticbeanstalk-us-east-1-400788082106'
  bucket_path: 'docker-react'
  on:
    repo: narcisonunez/docker-react
    branches:
      only:
        - master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
